<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block newsletter">
    <h6>SIGN UP AND STAY INFORMED</h6>
    <div class="content">
        <form class="form subscribe"
              novalidate
              action="<?php /* @escapeNotVerified */
              echo $block->getFormActionUrl() ?>"
              method="post"
              data-mage-init='{"validation": {"errorClass": "mage-error"}}'
              id="newsletter-validate-detail">
            <ul>
                <li>
                    <div class="input-group">
                        <span class="input-group-btn">
                            <button class="action btn btn-secondary subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                                <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
                            </button>
                        </span>
                        <input name="email"
                               class="form-control"
                               type="email" id="newsletter"
                               placeholder="<?php /* @escapeNotVerified */
                               echo __('Your email') ?>"
                               data-validate="{required:true, 'validate-email':true}"/>

                    </div>
                </li>
            </ul>
        </form>
    </div>
</div>

