<?php
/**
 * Bulk order template
 *
 * @var $block \BroSolutions\BulkOrder\Block\Index
 */
$rowsCount = $block->getRowsCount();
$colsCount = $block->getColsCount();
?>
<form id="bulk-order-form" method="post" action="<?php echo $block->getFormAction(); ?>" data-mage-init='{"validation": {}}'>

    <h1>Place Bulk Order</h1>
    <p><?php echo __('Quickly add items to your cart by entering item numbers and quantities.'); ?></p>

    <table id="bopPageLineByLineTable" class="table">
    <thead>
    <tr>
        <th class="left labelItem bulkorderItem">
            <?php echo __('Item #')?></th>
        <th class="left bulkorderQuantity">
            <?php echo __('Qty')?></th>
        <th class="left labelItem bulkorderItem">
            <?php echo __('Item #')?></th>
        <th class="left bulkorderQuantity">
            <?php echo __('Qty')?></th>
        <th class="left labelItem bulkorderItem">
            <?php echo __('Item #')?></th>
        <th class="left bulkorderQuantity">
            <?php echo __('Qty')?></th>
    </tr>
    </thead>
    <tbody>
    <?php for($i = 0; $i < $rowsCount; $i++): ?>
        <tr>
            <?php for($j = 0; $j < $colsCount; $j++): ?>
                <td class="productItemNumber" width="28%"><input  name="sku[]" title="Item #" tabindex="1" type="text" value="" maxlength="10"></td>
                <td class="productQuantity" width="5.33%"><input  lass="input-text" name="qty[]" title="Qty" tabindex="1" value="1" type="text" maxlength="4"
                   data-validate="{required:true, 'validate-integers':true}"></td>
            <?php endfor; ?>
        </tr>
        <?php endfor; ?>
    </tbody>
</table>

<button type="submit" title="Add to Cart" class="btn yellow-btn">
    <span><?php echo __('Add to Cart')?></span>
</button>

</form>
<script type="text/javascript">
    require([
        'jquery',
        'jquery/ui',
        'jquery/validate',
        'mage/translate'
    ], function($){
        $.validator.addMethod(
            'validate-integers', function (value) {
                console.log(value);
                var isInteger = (Math.floor(value) == value && $.isNumeric(value));
                return isInteger && (value > 0);
            }, $.mage.__('Please enter valid qty'));

    });
</script>
